version: "3.9"

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  api-1:
    image: tbrunia/todd-coin:latest
    depends_on:
      - db
    restart: always
    ports:
      - "3001:3001"
    environment:
      DB_NAME: todd-coin-1
      DB_USERNAME: postgres
      DB_PASSWORD: secret
      DB_HOST: db
      DB_PORT: 5432
      API_HOST: 0.0.0.0
      API_PORT: 3001
      API_BASE_URL: http://localhost:3001
  api-2:
    image: tbrunia/todd-coin:latest
    depends_on:
      - db
    restart: always
    ports:
      - "3002:3002"
    environment:
      DB_NAME: todd-coin-2
      DB_USERNAME: postgres
      DB_PASSWORD: secret
      DB_HOST: db
      DB_PORT: 5432
      API_HOST: 0.0.0.0
      API_PORT: 3002
      API_BASE_URL: http://localhost:3002
  api-3:
    image: tbrunia/todd-coin:latest
    depends_on:
      - db
    restart: always
    ports:
      - "3003:3003"
    environment:
      DB_NAME: todd-coin-3
      DB_USERNAME: postgres
      DB_PASSWORD: secret
      DB_HOST: db
      DB_PORT: 5432
      API_HOST: 0.0.0.0
      API_PORT: 3003
      API_BASE_URL: http://localhost:3003
  api-4:
    image: tbrunia/todd-coin:latest
    depends_on:
      - db
    restart: always
    ports:
      - "3004:3004"
    environment:
      DB_NAME: todd-coin-4
      DB_USERNAME: postgres
      DB_PASSWORD: secret
      DB_HOST: db
      DB_PORT: 5432
      API_HOST: 0.0.0.0
      API_PORT: 3004
      API_BASE_URL: http://localhost:3004
  api-5:
    image: tbrunia/todd-coin:latest
    depends_on:
      - db
    restart: always
    ports:
      - "3005:3005"
    environment:
      DB_NAME: todd-coin-5
      DB_USERNAME: postgres
      DB_PASSWORD: secret
      DB_HOST: db
      DB_PORT: 5432
      API_HOST: 0.0.0.0
      API_PORT: 3005
      API_BASE_URL: http://localhost:3005
volumes:
  pgdata:
