version: "3.9"

services:
  grafana:
    image: grafana/grafana
    ports:
      - "3100:3000"
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - ~/.todd-coin/pg-data:/var/lib/postgresql/data
  api:
    image: xilution/todd-coin-api:latest
    depends_on:
      - db
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_NAME: todd-coin
      DB_USERNAME: postgres
      DB_PASSWORD: secret
      DB_HOST: db
      DB_PORT: 5432
      API_HOST: 0.0.0.0
      API_PORT: 3000
      API_BASE_URL: http://localhost:3000
  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    ports:
      - "9187:9187"
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:secret@postgres:5432/todd-coin?sslmode=disable"
    links:
      - db
      - prometheus
volumes:
  pg-data:
