import Joi from "joi";
import {
  AUTHORIZATION_SCHEMA,
  CREATE_BLOCK_SCHEMA,
  CREATE_NODE_SCHEMA,
  CREATE_ORGANIZATION_PARTICIPANT_REFERENCE_SCHEMA,
  CREATE_ORGANIZATION_SCHEMA,
  CREATE_PARTICIPANT_KEY_SCHEMA,
  CREATE_PARTICIPANT_ORGANIZATION_REFERENCE_SCHEMA,
  CREATE_PARTICIPANT_SCHEMA,
  CREATE_PENDING_TRANSACTION_SCHEMA,
  CREATE_SIGNED_TRANSACTION_SCHEMA,
  EMAIL_SCHEMA,
  ID_SCHEMA,
  PAGINATION_QUERY_SCHEMA,
  PASSWORD_SCHEMA,
  PUBLIC_KEY_SCHEMA,
  UPDATE_NODE_SCHEMA,
  UPDATE_ORGANIZATION_SCHEMA,
  UPDATE_PARTICIPANT_KEY_SCHEMA,
  UPDATE_PARTICIPANT_SCHEMA,
  UPDATE_PENDING_TRANSACTION_SCHEMA,
  UPDATE_SIGNED_TRANSACTION_SCHEMA,
} from "./shared-schemas";
import {
  BLOCK_ID_DESCRIPTION,
  BLOCK_TRANSACTION_ID_DESCRIPTION,
  FILTER_BY_FROM_PARTICIPANT_DESCRIPTION,
  FILTER_BY_PUBLIC_KEY_DESCRIPTION,
  FILTER_BY_TO_PARTICIPANT_DESCRIPTION,
  NODE_ID_DESCRIPTION,
  ORGANIZATION_ID_DESCRIPTION,
  PARTICIPANT_ID_DESCRIPTION,
  PARTICIPANT_KEY_ID_DESCRIPTION,
  PATCH_NODE_REQUEST_LABEL,
  PATCH_ORGANIZATION_REQUEST_LABEL,
  PATCH_PARTICIPANT_KEY_REQUEST_LABEL,
  PATCH_PARTICIPANT_REQUEST_LABEL,
  PATCH_PENDING_TRANSACTION_REQUEST_LABEL,
  PATCH_SIGNED_TRANSACTION_REQUEST_LABEL,
  PENDING_TRANSACTION_ID_DESCRIPTION,
  POST_BLOCK_REQUEST_LABEL,
  POST_NODE_REQUEST_LABEL,
  POST_ORGANIZATION_ADMINISTRATOR_REF_REQUEST_LABEL,
  POST_ORGANIZATION_AUTHORIZED_SIGNER_REF_REQUEST_LABEL,
  POST_ORGANIZATION_PARTICIPANT_REF_REQUEST_LABEL,
  POST_ORGANIZATION_REQUEST_LABEL,
  POST_PARTICIPANT_KEY_REQUEST_LABEL,
  POST_PARTICIPANT_ORGANIZATION_REF_REQUEST_LABEL,
  POST_PARTICIPANT_REQUEST_LABEL,
  POST_PENDING_TRANSACTION_REQUEST_LABEL,
  POST_SIGNED_TRANSACTION_REQUEST_LABEL,
  SIGNED_TRANSACTION_ID_DESCRIPTION,
} from "./messages";

export const AUTH_HEADER_SCHEMA = Joi.object({
  authorization: AUTHORIZATION_SCHEMA.required(),
}).unknown();

export const GET_BLOCKS_QUERY_SCHEMA = PAGINATION_QUERY_SCHEMA;

export const GET_BLOCK_PARAMETERS_SCHEMA = Joi.object({
  blockId: ID_SCHEMA.description(BLOCK_ID_DESCRIPTION),
});

export const GET_PENDING_TRANSACTIONS_QUERY_SCHEMA =
  PAGINATION_QUERY_SCHEMA.keys({
    "filter[from]": ID_SCHEMA.description(
      FILTER_BY_FROM_PARTICIPANT_DESCRIPTION
    ),
    "filter[to]": ID_SCHEMA.description(FILTER_BY_TO_PARTICIPANT_DESCRIPTION),
  });

export const GET_PENDING_TRANSACTION_PARAMETERS_SCHEMA = Joi.object({
  pendingTransactionId: ID_SCHEMA.description(
    PENDING_TRANSACTION_ID_DESCRIPTION
  ),
});

export const DELETE_PENDING_TRANSACTION_PARAMETERS_SCHEMA = Joi.object({
  pendingTransactionId: ID_SCHEMA.description(
    PENDING_TRANSACTION_ID_DESCRIPTION
  ),
});

export const GET_SIGNED_TRANSACTIONS_QUERY_SCHEMA = PAGINATION_QUERY_SCHEMA;

export const GET_SIGNED_TRANSACTION_PARAMETERS_SCHEMA = Joi.object({
  signedTransactionId: ID_SCHEMA.description(SIGNED_TRANSACTION_ID_DESCRIPTION),
});

export const GET_BLOCK_TRANSACTIONS_QUERY_SCHEMA = PAGINATION_QUERY_SCHEMA;

export const GET_BLOCK_TRANSACTIONS_PARAMETERS_SCHEMA = Joi.object({
  blockId: ID_SCHEMA.description(BLOCK_ID_DESCRIPTION),
});

export const GET_BLOCK_TRANSACTION_PARAMETERS_SCHEMA = Joi.object({
  blockId: ID_SCHEMA.description(BLOCK_ID_DESCRIPTION),
  blockTransactionId: ID_SCHEMA.description(BLOCK_TRANSACTION_ID_DESCRIPTION),
});

export const GET_PARTICIPANTS_QUERY_SCHEMA = PAGINATION_QUERY_SCHEMA.keys({
  "filter[publicKey]": PUBLIC_KEY_SCHEMA.description(
    FILTER_BY_PUBLIC_KEY_DESCRIPTION
  ),
});

export const GET_PARTICIPANT_PARAMETERS_SCHEMA = Joi.object({
  participantId: ID_SCHEMA.description(PARTICIPANT_ID_DESCRIPTION),
});

export const GET_PARTICIPANT_KEYS_PARAMETERS_SCHEMA = Joi.object({
  participantId: ID_SCHEMA.description(PARTICIPANT_ID_DESCRIPTION),
});

export const GET_PARTICIPANT_KEY_PARAMETERS_SCHEMA = Joi.object({
  participantId: ID_SCHEMA.description(PARTICIPANT_ID_DESCRIPTION),
  participantKeyId: ID_SCHEMA.description(PARTICIPANT_KEY_ID_DESCRIPTION),
});

export const POST_PARTICIPANT_KEYS_PARAMETERS_SCHEMA = Joi.object({
  participantId: ID_SCHEMA.description(PARTICIPANT_ID_DESCRIPTION),
});

export const PATCH_PARTICIPANT_KEYS_PARAMETERS_SCHEMA = Joi.object({
  participantId: ID_SCHEMA.description(PARTICIPANT_ID_DESCRIPTION),
  participantKeyId: ID_SCHEMA.description(PARTICIPANT_KEY_ID_DESCRIPTION),
});

export const GET_NODES_QUERY_SCHEMA = PAGINATION_QUERY_SCHEMA;

export const GET_NODE_PARAMETERS_SCHEMA = Joi.object({
  nodeId: ID_SCHEMA.description(NODE_ID_DESCRIPTION),
});

export const GET_ORGANIZATIONS_QUERY_SCHEMA = PAGINATION_QUERY_SCHEMA;

export const GET_ORGANIZATION_PARAMETERS_SCHEMA = Joi.object({
  organizationId: ID_SCHEMA.description(ORGANIZATION_ID_DESCRIPTION),
});

export const DELETE_ORGANIZATION_PARTICIPANT_PARAMETERS_SCHEMA = Joi.object({
  organizationId: ID_SCHEMA.description(ORGANIZATION_ID_DESCRIPTION),
  participantId: ID_SCHEMA.description(PARTICIPANT_ID_DESCRIPTION),
});

export const DELETE_ORGANIZATION_AUTHORIZED_SIGNER_PARAMETERS_SCHEMA =
  Joi.object({
    organizationId: ID_SCHEMA.description(ORGANIZATION_ID_DESCRIPTION),
    authorizedSignerId: ID_SCHEMA.description(PARTICIPANT_ID_DESCRIPTION),
  });

export const DELETE_ORGANIZATION_ADMINISTRATOR_PARAMETERS_SCHEMA = Joi.object({
  organizationId: ID_SCHEMA.description(ORGANIZATION_ID_DESCRIPTION),
  administratorId: ID_SCHEMA.description(PARTICIPANT_ID_DESCRIPTION),
});

export const DELETE_PARTICIPANT_ORGANIZATION_PARAMETERS_SCHEMA = Joi.object({
  participantId: ID_SCHEMA.description(PARTICIPANT_ID_DESCRIPTION),
  organizationId: ID_SCHEMA.description(ORGANIZATION_ID_DESCRIPTION),
});

export const POST_PENDING_TRANSACTION_REQUEST_SCHEMA = Joi.object({
  data: CREATE_PENDING_TRANSACTION_SCHEMA,
})
  .unknown(false)
  .label(POST_PENDING_TRANSACTION_REQUEST_LABEL);

export const PATCH_PENDING_TRANSACTION_REQUEST_SCHEMA = Joi.object({
  data: UPDATE_PENDING_TRANSACTION_SCHEMA,
})
  .unknown(false)
  .label(PATCH_PENDING_TRANSACTION_REQUEST_LABEL);

export const POST_SIGNED_TRANSACTION_REQUEST_SCHEMA = Joi.object({
  data: CREATE_SIGNED_TRANSACTION_SCHEMA,
})
  .unknown(false)
  .label(POST_SIGNED_TRANSACTION_REQUEST_LABEL);

export const PATCH_SIGNED_TRANSACTION_REQUEST_SCHEMA = Joi.object({
  data: UPDATE_SIGNED_TRANSACTION_SCHEMA,
})
  .unknown(false)
  .label(PATCH_SIGNED_TRANSACTION_REQUEST_LABEL);

export const POST_BLOCK_REQUEST_SCHEMA = Joi.object({
  data: CREATE_BLOCK_SCHEMA,
})
  .unknown(false)
  .label(POST_BLOCK_REQUEST_LABEL);

export const POST_PARTICIPANT_REQUEST_SCHEMA = Joi.object({
  data: CREATE_PARTICIPANT_SCHEMA,
})
  .unknown(false)
  .label(POST_PARTICIPANT_REQUEST_LABEL);

export const PATCH_PARTICIPANT_REQUEST_SCHEMA = Joi.object({
  data: UPDATE_PARTICIPANT_SCHEMA,
})
  .unknown(false)
  .label(PATCH_PARTICIPANT_REQUEST_LABEL);

export const POST_PARTICIPANT_KEY_REQUEST_SCHEMA = Joi.object({
  data: CREATE_PARTICIPANT_KEY_SCHEMA,
})
  .unknown(false)
  .label(POST_PARTICIPANT_KEY_REQUEST_LABEL);

export const PATCH_PARTICIPANT_KEY_REQUEST_SCHEMA = Joi.object({
  data: UPDATE_PARTICIPANT_KEY_SCHEMA,
})
  .unknown(false)
  .label(PATCH_PARTICIPANT_KEY_REQUEST_LABEL);

export const POST_NODE_REQUEST_SCHEMA = Joi.object({
  data: CREATE_NODE_SCHEMA,
})
  .unknown(false)
  .label(POST_NODE_REQUEST_LABEL);

export const PATCH_NODE_REQUEST_SCHEMA = Joi.object({
  data: UPDATE_NODE_SCHEMA,
})
  .unknown(false)
  .label(PATCH_NODE_REQUEST_LABEL);

export const POST_ORGANIZATION_REQUEST_SCHEMA = Joi.object({
  data: CREATE_ORGANIZATION_SCHEMA,
})
  .unknown(false)
  .label(POST_ORGANIZATION_REQUEST_LABEL);

export const PATCH_ORGANIZATION_REQUEST_SCHEMA = Joi.object({
  data: UPDATE_ORGANIZATION_SCHEMA,
})
  .unknown(false)
  .label(PATCH_ORGANIZATION_REQUEST_LABEL);

export const POST_ORGANIZATION_PARTICIPANTS_REQUEST_SCHEMA = Joi.object({
  data: CREATE_ORGANIZATION_PARTICIPANT_REFERENCE_SCHEMA,
})
  .unknown(false)
  .label(POST_ORGANIZATION_PARTICIPANT_REF_REQUEST_LABEL);

export const POST_ORGANIZATION_AUTHORIZED_SIGNERS_REQUEST_SCHEMA = Joi.object({
  data: CREATE_ORGANIZATION_PARTICIPANT_REFERENCE_SCHEMA,
})
  .unknown(false)
  .label(POST_ORGANIZATION_AUTHORIZED_SIGNER_REF_REQUEST_LABEL);

export const POST_ORGANIZATION_ADMINISTRATORS_REQUEST_SCHEMA = Joi.object({
  data: CREATE_ORGANIZATION_PARTICIPANT_REFERENCE_SCHEMA,
})
  .unknown(false)
  .label(POST_ORGANIZATION_ADMINISTRATOR_REF_REQUEST_LABEL);

export const POST_PARTICIPANTS_ORGANIZATION_REQUEST_SCHEMA = Joi.object({
  data: CREATE_PARTICIPANT_ORGANIZATION_REFERENCE_SCHEMA,
})
  .unknown(false)
  .label(POST_PARTICIPANT_ORGANIZATION_REF_REQUEST_LABEL);

export const AUTH_TOKEN_REQUEST_SCHEMA = Joi.object({
  email: EMAIL_SCHEMA.required(),
  password: PASSWORD_SCHEMA.required(),
}).unknown(false);
