import Joi from "joi";
import {
  ACCESS_TOKEN_SCHEMA,
  buildReturnManyLinks,
  buildReturnOneLinks,
  GET_MANY_META_SCHEMA,
  JSON_API_SCHEMA,
  READ_BLOCK_SCHEMA,
  READ_BLOCK_TRANSACTION_SCHEMA,
  READ_NODE_SCHEMA,
  READ_ORGANIZATION_SCHEMA,
  READ_PARTICIPANT_KEY_SCHEMA,
  READ_PARTICIPANT_SCHEMA,
  READ_PENDING_TRANSACTION_SCHEMA,
  READ_SIGNED_TRANSACTION_SCHEMA,
} from "./shared-schemas";
import {
  AUTH_TOKEN_RESPONSE_LABEL,
  BLOCK_TRANSACTIONS_DATA_LABEL,
  BLOCKS_DATA,
  DETAIL_LABEL,
  ERROR_DETAIL_DESCRIPTION,
  ERROR_LABEL,
  ERROR_SOURCE_DESCRIPTION,
  ERROR_SOURCE_PARAMETER_DESCRIPTION,
  ERROR_SOURCE_POINTER_DESCRIPTION,
  ERROR_STATUS_DESCRIPTION,
  ERROR_TITLE_DESCRIPTION,
  ERRORS_LABEL,
  GET_BLOCK_LINKS_LABEL,
  GET_BLOCK_RESPONSE_LABEL,
  GET_BLOCK_TRANSACTION_LINKS_LABEL,
  GET_BLOCK_TRANSACTION_RESPONSE_LABEL,
  GET_BLOCK_TRANSACTIONS_LINKS_LABEL,
  GET_BLOCK_TRANSACTIONS_RESPONSE_LABEL,
  GET_BLOCKS_LINKS_LABEL,
  GET_BLOCKS_RESPONSE_LABEL,
  GET_NODE_LINKS_LABEL,
  GET_NODE_RESPONSE_LABEL,
  GET_NODES_LINKS_LABEL,
  GET_NODES_RESPONSE_LABEL,
  GET_ORGANIZATION_LINKS_LABEL,
  GET_ORGANIZATION_RESPONSE_LABEL,
  GET_ORGANIZATIONS_LINKS_LABEL,
  GET_ORGANIZATIONS_RESPONSE_LABEL,
  GET_PARTICIPANT_KEY_LINKS_LABEL,
  GET_PARTICIPANT_KEY_RESPONSE_LABEL,
  GET_PARTICIPANT_KEYS_LINKS_LABEL,
  GET_PARTICIPANT_KEYS_RESPONSE_LABEL,
  GET_PARTICIPANT_LINKS_LABEL,
  GET_PARTICIPANT_RESPONSE_LABEL,
  GET_PARTICIPANTS_LINKS_LABEL,
  GET_PARTICIPANTS_RESPONSE_LABEL,
  GET_PENDING_TRANSACTION_LINKS_LABEL,
  GET_PENDING_TRANSACTION_RESPONSE_LABEL,
  GET_PENDING_TRANSACTIONS_LINKS_LABEL,
  GET_PENDING_TRANSACTIONS_RESPONSE_LABEL,
  GET_SIGNED_TRANSACTION_LINKS_LABEL,
  GET_SIGNED_TRANSACTION_RESPONSE_LABEL,
  GET_SIGNED_TRANSACTIONS_LINKS_LABEL,
  GET_SIGNED_TRANSACTIONS_RESPONSE_LABEL,
  NODES_DATA_LABEL,
  ORGANIZATIONS_DATA_LABEL,
  PARAMETER_LABEL,
  PARTICIPANT_KEYS_DATA_LABEL,
  PARTICIPANTS_DATA_LABEL,
  PENDING_TRANSACTIONS_DATA_LABEL,
  POINTER_LABEL,
  POST_BLOCK_LINKS_LABEL,
  POST_BLOCK_RESPONSE_LABEL,
  POST_NODE_LINKS_LABEL,
  POST_NODE_RESPONSE_LABEL,
  POST_ORGANIZATION_LINKS_LABEL,
  POST_ORGANIZATION_RESPONSE_LABEL,
  POST_PARTICIPANT_KEY_LINKS_LABEL,
  POST_PARTICIPANT_KEY_RESPONSE_LABEL,
  POST_PARTICIPANT_LINKS_LABEL,
  POST_PARTICIPANT_RESPONSE_LABEL,
  POST_PENDING_TRANSACTION_LINKS_LABEL,
  POST_PENDING_TRANSACTION_RESPONSE_LABEL,
  POST_SIGNED_TRANSACTION_LINKS_LABEL,
  POST_SIGNED_TRANSACTION_RESPONSE_LABEL,
  SIGNED_TRANSACTIONS_DATA_LABEL,
  SOURCE_LABEL,
  STATUS_LABEL,
  TITLE_LABEL,
} from "./messages";

const API_BASE_URL = "${API_BASE_URL}";

export const AUTH_TOKEN_RESPONSE_SCHEMA = Joi.object({
  access: ACCESS_TOKEN_SCHEMA,
}).label(AUTH_TOKEN_RESPONSE_LABEL);

export const GET_BLOCK_TRANSACTIONS_RESPONSE_SCHEMA = Joi.object({
  jsonapi: JSON_API_SCHEMA,
  meta: GET_MANY_META_SCHEMA,
  links: buildReturnManyLinks(
    `${API_BASE_URL}/blocks/b3af823a-cb10-4c04-bb42-b055dd005992/block-transactions`
  ).label(GET_BLOCK_TRANSACTIONS_LINKS_LABEL),
  data: Joi.array()
    .items(READ_BLOCK_TRANSACTION_SCHEMA)
    .label(BLOCK_TRANSACTIONS_DATA_LABEL),
}).label(GET_BLOCK_TRANSACTIONS_RESPONSE_LABEL);

export const GET_BLOCK_TRANSACTION_RESPONSE_SCHEMA = Joi.object({
  jsonapi: JSON_API_SCHEMA,
  links: buildReturnOneLinks(
    `${API_BASE_URL}/blocks/4ddfd4a9-df0e-40dc-98fc-a8987e842a21/block-transactions/f56825d3-c7a6-4c14-963e-ce4a4714d021`
  ).label(GET_BLOCK_TRANSACTION_LINKS_LABEL),
  data: READ_BLOCK_TRANSACTION_SCHEMA,
}).label(GET_BLOCK_TRANSACTION_RESPONSE_LABEL);

export const GET_BLOCKS_RESPONSE_SCHEMA = Joi.object({
  jsonapi: JSON_API_SCHEMA,
  meta: GET_MANY_META_SCHEMA,
  links: buildReturnManyLinks(`${API_BASE_URL}/blocks`).label(
    GET_BLOCKS_LINKS_LABEL
  ),
  data: Joi.array().items(READ_BLOCK_SCHEMA).label(BLOCKS_DATA),
}).label(GET_BLOCKS_RESPONSE_LABEL);

export const GET_BLOCK_RESPONSE_SCHEMA = Joi.object({
  jsonapi: JSON_API_SCHEMA,
  links: buildReturnOneLinks(
    `${API_BASE_URL}/blocks/9466fe6b-4b94-48ab-a52d-ef47abda9dfb`
  ).label(GET_BLOCK_LINKS_LABEL),
  data: READ_BLOCK_SCHEMA,
}).label(GET_BLOCK_RESPONSE_LABEL);

export const POST_BLOCK_RESPONSE_SCHEMA = Joi.object({
  jsonapi: JSON_API_SCHEMA,
  links: buildReturnOneLinks(
    `${API_BASE_URL}/blocks/27f437fc-7e05-41f7-81ec-b14441e2ac56`
  ).label(POST_BLOCK_LINKS_LABEL),
  data: READ_BLOCK_SCHEMA,
}).label(POST_BLOCK_RESPONSE_LABEL);

export const GET_NODES_RESPONSE_SCHEMA = Joi.object({
  jsonapi: JSON_API_SCHEMA,
  meta: GET_MANY_META_SCHEMA,
  links: buildReturnManyLinks(`${API_BASE_URL}/nodes`).label(
    GET_NODES_LINKS_LABEL
  ),
  data: Joi.array().items(READ_NODE_SCHEMA).label(NODES_DATA_LABEL),
}).label(GET_NODES_RESPONSE_LABEL);

export const GET_NODE_RESPONSE_SCHEMA = Joi.object({
  jsonapi: JSON_API_SCHEMA,
  links: buildReturnOneLinks(
    `${API_BASE_URL}/nodes/ef7e62d0-70d6-4252-9ba0-a59a3b02f5de`
  ).label(GET_NODE_LINKS_LABEL),
  data: READ_NODE_SCHEMA,
}).label(GET_NODE_RESPONSE_LABEL);

export const POST_NODE_RESPONSE_SCHEMA = Joi.object({
  jsonapi: JSON_API_SCHEMA,
  links: buildReturnOneLinks(
    `${API_BASE_URL}/nodes/aa233a64-dc34-4fbb-a6ce-3bc7ca640064`
  ).label(POST_NODE_LINKS_LABEL),
  data: READ_NODE_SCHEMA,
}).label(POST_NODE_RESPONSE_LABEL);

export const GET_ORGANIZATIONS_RESPONSE_SCHEMA = Joi.object({
  jsonapi: JSON_API_SCHEMA,
  meta: GET_MANY_META_SCHEMA,
  links: buildReturnManyLinks(`${API_BASE_URL}/organizations`).label(
    GET_ORGANIZATIONS_LINKS_LABEL
  ),
  data: Joi.array()
    .items(READ_ORGANIZATION_SCHEMA)
    .label(ORGANIZATIONS_DATA_LABEL),
}).label(GET_ORGANIZATIONS_RESPONSE_LABEL);

export const GET_ORGANIZATION_RESPONSE_SCHEMA = Joi.object({
  jsonapi: JSON_API_SCHEMA,
  links: buildReturnOneLinks(
    `${API_BASE_URL}/organizations/bb47b3e6-bede-42c6-9319-193f1a7f9f45`
  ).label(GET_ORGANIZATION_LINKS_LABEL),
  data: READ_ORGANIZATION_SCHEMA,
}).label(GET_ORGANIZATION_RESPONSE_LABEL);

export const POST_ORGANIZATION_RESPONSE_SCHEMA = Joi.object({
  jsonapi: JSON_API_SCHEMA,
  links: buildReturnOneLinks(
    `${API_BASE_URL}/organizations/97851eba-fd4b-438e-8fa8-fdaeb0236fdf`
  ).label(POST_ORGANIZATION_LINKS_LABEL),
  data: READ_ORGANIZATION_SCHEMA,
}).label(POST_ORGANIZATION_RESPONSE_LABEL);

export const GET_PARTICIPANT_KEYS_RESPONSE_SCHEMA = Joi.object({
  jsonapi: JSON_API_SCHEMA,
  meta: GET_MANY_META_SCHEMA,
  links: buildReturnManyLinks(`${API_BASE_URL}/participant-keys`).label(
    GET_PARTICIPANT_KEYS_LINKS_LABEL
  ),
  data: Joi.array()
    .items(READ_PARTICIPANT_KEY_SCHEMA)
    .label(PARTICIPANT_KEYS_DATA_LABEL),
}).label(GET_PARTICIPANT_KEYS_RESPONSE_LABEL);

export const GET_PARTICIPANT_KEY_RESPONSE_SCHEMA = Joi.object({
  jsonapi: JSON_API_SCHEMA,
  links: buildReturnOneLinks(
    `${API_BASE_URL}/participant-keys/63a6c04a-6838-4c42-bda8-781af29f5ecd`
  ).label(GET_PARTICIPANT_KEY_LINKS_LABEL),
  data: READ_PARTICIPANT_KEY_SCHEMA,
}).label(GET_PARTICIPANT_KEY_RESPONSE_LABEL);

export const POST_PARTICIPANT_KEY_RESPONSE_SCHEMA = Joi.object({
  jsonapi: JSON_API_SCHEMA,
  links: buildReturnOneLinks(
    `${API_BASE_URL}/participant-keys/50020051-cd8b-4dd2-8fc7-a12ba84b6e71`
  ).label(POST_PARTICIPANT_KEY_LINKS_LABEL),
  data: READ_PARTICIPANT_KEY_SCHEMA,
}).label(POST_PARTICIPANT_KEY_RESPONSE_LABEL);

export const GET_PARTICIPANTS_RESPONSE_SCHEMA = Joi.object({
  jsonapi: JSON_API_SCHEMA,
  meta: GET_MANY_META_SCHEMA,
  links: buildReturnManyLinks(`${API_BASE_URL}/participants`).label(
    GET_PARTICIPANTS_LINKS_LABEL
  ),
  data: Joi.array()
    .items(READ_PARTICIPANT_SCHEMA)
    .label(PARTICIPANTS_DATA_LABEL),
}).label(GET_PARTICIPANTS_RESPONSE_LABEL);

export const GET_PARTICIPANT_RESPONSE_SCHEMA = Joi.object({
  jsonapi: JSON_API_SCHEMA,
  links: buildReturnOneLinks(
    `${API_BASE_URL}/participants/39c9eaa9-9389-4f68-bdc6-c92006a431e5`
  ).label(GET_PARTICIPANT_LINKS_LABEL),
  data: READ_PARTICIPANT_SCHEMA,
}).label(GET_PARTICIPANT_RESPONSE_LABEL);

export const POST_PARTICIPANT_RESPONSE_SCHEMA = Joi.object({
  jsonapi: JSON_API_SCHEMA,
  links: buildReturnOneLinks(
    `${API_BASE_URL}/participants/1a1e3a70-6657-4c6a-8c13-b6abc0aa4b2e`
  ).label(POST_PARTICIPANT_LINKS_LABEL),
  data: READ_PARTICIPANT_SCHEMA,
}).label(POST_PARTICIPANT_RESPONSE_LABEL);

export const GET_PENDING_TRANSACTIONS_RESPONSE_SCHEMA = Joi.object({
  jsonapi: JSON_API_SCHEMA,
  meta: GET_MANY_META_SCHEMA,
  links: buildReturnManyLinks(`${API_BASE_URL}/pending-transactions`).label(
    GET_PENDING_TRANSACTIONS_LINKS_LABEL
  ),
  data: Joi.array()
    .items(READ_PENDING_TRANSACTION_SCHEMA)
    .label(PENDING_TRANSACTIONS_DATA_LABEL),
}).label(GET_PENDING_TRANSACTIONS_RESPONSE_LABEL);

export const GET_PENDING_TRANSACTION_RESPONSE_SCHEMA = Joi.object({
  jsonapi: JSON_API_SCHEMA,
  links: buildReturnOneLinks(
    `${API_BASE_URL}/pending-transactions/4d4da69d-4576-4c6e-bcb5-4885a26a8abf`
  ).label(GET_PENDING_TRANSACTION_LINKS_LABEL),
  data: READ_PENDING_TRANSACTION_SCHEMA,
}).label(GET_PENDING_TRANSACTION_RESPONSE_LABEL);

export const POST_PENDING_TRANSACTION_RESPONSE_SCHEMA = Joi.object({
  jsonapi: JSON_API_SCHEMA,
  links: buildReturnOneLinks(
    `${API_BASE_URL}/pending-transactions/d18b33b2-b40f-40c0-96fc-bf03581eda28`
  ).label(POST_PENDING_TRANSACTION_LINKS_LABEL),
  data: READ_PENDING_TRANSACTION_SCHEMA,
}).label(POST_PENDING_TRANSACTION_RESPONSE_LABEL);

export const GET_SIGNED_TRANSACTIONS_RESPONSE_SCHEMA = Joi.object({
  jsonapi: JSON_API_SCHEMA,
  meta: GET_MANY_META_SCHEMA,
  links: buildReturnManyLinks(`${API_BASE_URL}/signed-transactions`).label(
    GET_SIGNED_TRANSACTIONS_LINKS_LABEL
  ),
  data: Joi.array()
    .items(READ_SIGNED_TRANSACTION_SCHEMA)
    .label(SIGNED_TRANSACTIONS_DATA_LABEL),
}).label(GET_SIGNED_TRANSACTIONS_RESPONSE_LABEL);

export const GET_SIGNED_TRANSACTION_RESPONSE_SCHEMA = Joi.object({
  jsonapi: JSON_API_SCHEMA,
  links: buildReturnOneLinks(
    `${API_BASE_URL}/signed-transactions/76a999d5-e478-44f2-a558-b33671f83794`
  ).label(GET_SIGNED_TRANSACTION_LINKS_LABEL),
  data: READ_SIGNED_TRANSACTION_SCHEMA,
}).label(GET_SIGNED_TRANSACTION_RESPONSE_LABEL);

export const POST_SIGNED_TRANSACTION_RESPONSE_SCHEMA = Joi.object({
  jsonapi: JSON_API_SCHEMA,
  links: buildReturnOneLinks(
    `${API_BASE_URL}/signed-transactions/82025a3d-ac3f-4554-89f2-055fe263cffd`
  ).label(POST_SIGNED_TRANSACTION_LINKS_LABEL),
  data: READ_SIGNED_TRANSACTION_SCHEMA,
}).label(POST_SIGNED_TRANSACTION_RESPONSE_LABEL);

export const ERROR_RESPONSE_SCHEMA = Joi.object({
  jsonapi: JSON_API_SCHEMA,
  errors: Joi.array()
    .items(
      Joi.object({
        status: Joi.string()
          .description(ERROR_STATUS_DESCRIPTION)
          .label(STATUS_LABEL),
        title: Joi.string()
          .description(ERROR_TITLE_DESCRIPTION)
          .label(TITLE_LABEL),
        source: Joi.object({
          pointer: Joi.string()
            .description(ERROR_SOURCE_POINTER_DESCRIPTION)
            .label(POINTER_LABEL),
          parameter: Joi.string()
            .description(ERROR_SOURCE_PARAMETER_DESCRIPTION)
            .label(PARAMETER_LABEL),
        })
          .description(ERROR_SOURCE_DESCRIPTION)
          .label(SOURCE_LABEL),
        detail: Joi.string()
          .description(ERROR_DETAIL_DESCRIPTION)
          .label(DETAIL_LABEL),
      }).label(ERROR_LABEL)
    )
    .label(ERRORS_LABEL),
});
